plugins {
    id 'com.android.library'
}

android {
    namespace 'com.vermajeeverma.turborush.ads'
    compileSdk 36

    defaultConfig {
        minSdk 24
        consumerProguardFiles 'consumer-rules.pro'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig true
    }

    publishing {
        singleVariant('release')
    }
}

dependencies {
    implementation 'org.godotengine:godot:4.7.2.stable'
    implementation 'com.unity3d.ads:unity-ads:4.20.1'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
